name: 'Publish storybook to chromatic'

on:
  push:
    branches: [ develop, master ]

jobs:
  chromatic:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./SmashCombos.Client
    steps:
      - uses: actions/checkout@v1
      - run: yarn install
      - run: |
          yarn build-storybook
          CHROMATIC_PROJECT_TOKEN=${{ secrets.CHROMATIC_PROJECT_TOKEN }} npx chromatic --exit-zero-on-changes -d storybook-static/
