name: .NET Backend

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build project
      run: dotnet build --no-restore
      
    - name: Test project
      run: dotnet test --no-build --verbosity normal
      
    - name: Notify on failure
      uses: rjstone/discord-webhook-notify@v1
      if: failure()
      with:
        severity: error
        username: Github CI Police
        color: '#e53b37'
        avatarUrl: https://img.icons8.com/doodle/240/000000/github--v1.png
        details: 'Continuous Integration for the backend API failed.'
        footer: Please Fix
        text: Backend CI failed!
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK_TEST_FAILED }}
