name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Notify Discord if a test fail
      uses: rjstone/discord-webhook-notify@v1
      if: failure()
      with:
        severity: error
        username: Github CI Police
        color: '#e53b37'
        avatarUrl: https://img.icons8.com/doodle/240/000000/github--v1.png
        description: A test has failed in the server.
        details: 'Something broke in the backend'
        footer: pls fix asap
        text: Oh oh!
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK_TEST_FAILED }}
