name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Check workspace
      run: ls -la
    - name: Restore dependencies
      run: dotnet restore SmashCombos.Api/SmashCombos.Api.csproj
    - name: Build
      run: dotnet build --no-restore SmashCombos.Api/SmashCombos.Api.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal SmashCombos.Api/SmashCombos.Api.csproj
