name: Frontend pipeline

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./SmashHub.Client/smashhub-webapp

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install Dependencies
        run: yarn install && yarn build:component-library

      - name: E2E Test
        run: yarn run cypress run

      - uses: actions/checkout@v1

      - name: Unit/Integration Test
        working-directory: ./SmashHub.Client/smashhub-component-library
        run: yarn install && yarn test

      - name: Deploy to Chromatic
        working-directory: ./SmashHub.Client/smashhub-component-library
        run: |
          yarn build-storybook
          CHROMATIC_PROJECT_TOKEN=${{ secrets.CHROMATIC_PROJECT_TOKEN }} npx chromatic --exit-zero-on-changes -d storybook-static/

      - name: Notify on failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          username: Github CI Police
          color: "#e53b37"
          avatarUrl: https://img.icons8.com/doodle/240/000000/github--v1.png
          details: "Something broke in the frontend"
          footer: pls fix asap
          text: Oh oh!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_TEST_FAILED }}
