# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Dependencies
      run: |
        cd SmashCombos.Client
        yarn install
        yarn build-storybook
    
    - name: Unit/Integration Test
      run: |
        cd SmashCombos.Client
        yarn test
    
    - name: E2E Test 
      uses: cypress-io/github-action@v2
      with:
        start: npm start
        working-directory: SmashCombos.Client
    
    - name: Notify Discord if a test fail
      uses: rjstone/discord-webhook-notify@v1
      if: failure()
      with:
        severity: error
        username: Github CI Police
        color: '#e53b37'
        avatarUrl: https://img.icons8.com/doodle/240/000000/github--v1.png
        description: A test has failed in the client.
        details: 'Something broke in the frontend'
        footer: pls fix asap
        text: Oh oh!
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK_TEST_FAILED }}
