# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install Dependencies
        run: |
          cd SmashHub.Client/smashhub-web-app
          yarn install

      - name: E2E Test
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          working-directory: SmashHub.Client/smashhub-web-app

      - name: Notify on failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          username: Github CI Police
          color: "#e53b37"
          avatarUrl: https://img.icons8.com/doodle/240/000000/github--v1.png
          details: "Something broke in the frontend"
          footer: pls fix asap
          text: Oh oh!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_TEST_FAILED }}
